apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dm-worker
  namespace: dm-test-3
spec:
  selector:
    matchLabels:
      app: dm-worker
  serviceName: "dm-worker"
  replicas: 1
  template:
    metadata:
      labels:
        app: dm-worker
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: dm-worker
        image: hub.pingcap.net/dm/dm-worker:v1.0.2-rc1
        ports:
        - containerPort: 8262
          name: dm-worker
        env:
        - name: MYSQL_IPS
          valueFrom:
            configMapKeyRef:
              name: mysql-ips-config
              key: MYSQL_IPS
