# Data-Dam Configuration

rate = 5
duration = "1440h"
concurrent = 10
schemas = ["test_case2_1_indexPLC", "test_case2_indexPLC", "test_case2_3_indexPLC", "test_case2_4_indexPLC"]
op-weight = [2, 2, 1, 0]

[db-config.mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
enabled = true
