apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: dm-test-2
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 20
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-config-volume
        configMap:
          name: mysql-custom-config
  volumeClaimTemplates:
  - metadata:
      name: mysqldata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
      storageClassName: local-storage
