---
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # How frequently to evaluate rules.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    cluster: 'dm-test-2-cluster'
    monitor: "prometheus"

scrape_configs:
  - job_name: "dm_worker"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
