# Worker Configuration.

# log configuration
log-level = "info"

# log file path
log-file = "./log/dm-worker.log"

# dm-worker listen address
worker-addr = ":8262"

# server id of slave for binlog replication
# each instance (master and slave) in replication group should have different server id
server-id = 101

# represents a MySQL/MariaDB instance or a replication group
# replace this with ENV
source-id = "mysql-replica-01"

# flavor: mysql/mariadb
flavor = "mysql"

# directory that used to store relay log
relay-dir = "./relay_log"

# enable gtid in relay log unit
enable-gtid = false

# charset of DSN of source mysql/mariadb instance
# charset= ""

[from]
host = "127.0.0.1"
port = 3306
user = "root"
password = "VjX8cEeTX+qcvZ3bPaO4h0C80pe/1aU="

# relay log purge strategy
[purge]
interval = 3600
expires = 12
remain-space = 15
