apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-dam
  namespace: dm-test
spec:
  selector:
    matchLabels:
      app: data-dam
  serviceName: "data-dam"
  replicas: 20
  template:
    metadata:
      labels:
        app: data-dam
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: data-dam
        image: hub.pingcap.net/dm/data-dam:v0.1.2-rc1
        command: ["/home/tidb/bin/run-data-dam.sh"]
        env:
        - name: MYSQL_IPS
          valueFrom:
            configMapKeyRef:
              name: mysql-ips-config
              key: MYSQL_IPS
